//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R
{
    
    public sealed class Layers
    {
        public const int Default = 0;
        public const int Ignore_Raycast = 2;
        public const int TransparentFX = 1;
        public const int UI = 5;
        public const int Water = 4;
    }
    public sealed class LayerNames
    {
        public const string Default = "Default";
        public const string Ignore_Raycast = "Ignore Raycast";
        public const string TransparentFX = "TransparentFX";
        public const string UI = "UI";
        public const string Water = "Water";
    }
}
