//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R
{
    
    public sealed class SceneNames
    {
        public const string App = "App";
        public const string Level = "Level";
        public const string Lobby = "Lobby";
    }
}
